language: rust

sudo: false

rust:
  - nightly

cache: cargo

script:
  - cargo build
  - cargo build --example basic
  - cargo build --example multi_key

before_deploy:
  - cargo doc --no-deps --all-features

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: false
  local-dir: target/doc
  on:
    branch: master
    rust: nightly
