[package]
name = "flock"
version = "0.9.0"
authors = ["Dany Laporte <dany_laporte@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
failure = "0.1"
flock_derive = { path = "flock_derive" }
futures03 = { package = "futures", version = "0.3" }
indexmap = "1.3"
log = "0.4"
mssql_client = { git = "https://github.com/danylaporte/mssql_client.git" }
once_cell = "1.3"
parking_lot = "0.10"
rayon = "1.3"
serde = "1.0"
thread_local = "1.0"
tokio = { version = "0.2", features = ["macros", "rt-core", "rt-util", "sync"] }
uuid = { version = "0.8", features = ["serde", "v4"] }
version_tag = { git = "https://github.com/danylaporte/version_tag.git" }

[dev-dependencies]

[workspace]
members = [
    ".",
    "flock_derive"
]
