[package]
name = "flock_derive"
edition = "2018"
version = "0.1.0"
authors = ["Dany Laporte <dany_laporte@hotmail.com>"]

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "0.4"
quote = "0.6"
syn = { version = "0.15" }

[dev-dependencies]
