[package]
name = "flock_derive"
edition = "2018"
version = "0.11.4-alpha.0"
authors = ["Dany Laporte <dany_laporte@hotmail.com>"]
publish = false

[lib]
proc-macro = true

[dependencies]
Inflector = "0.11"
proc-macro2 = "1"
quote = "1"
syn = "1"

[dev-dependencies]
